# Generated by Django 4.2.2 on 2023-06-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('profissao', models.TextField(max_length=255)),
                ('nascimento', models.DateField()),
                ('plano_saude', models.TextField(max_length=255)),
                ('diagnostico', models.TextField(max_length=255)),
            ],
        ),
    ]
