# Generated by Django 5.1.4 on 2024-12-05 02:24

import app_cadastro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_trabajo', models.PositiveIntegerField(unique=True, validators=[app_cadastro.models.validate_unique_job_number], verbose_name='Número de Trabajo')),
                ('fecha_dia', models.DateField(auto_now_add=True, verbose_name='Fecha del Día')),
                ('fecha_retiro', models.DateField(verbose_name='Fecha en que el cliente puede retirar')),
                ('es_cliente', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], verbose_name='¿Es cliente?')),
                ('nombre_cliente', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domicilio')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('ojo_derecho_lejos_esf', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Derecho - Esf (Lejos)')),
                ('ojo_derecho_lejos_cil', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Derecho - Cil (Lejos)')),
                ('ojo_derecho_lejos_en', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Derecho - en (Lejos)')),
                ('ojo_derecho_lejos_dip', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Derecho - Dip (Lejos)')),
                ('ojo_izquierdo_lejos_esf', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Izquierdo - Esf (Lejos)')),
                ('ojo_izquierdo_lejos_cil', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Izquierdo - Cil (Lejos)')),
                ('ojo_izquierdo_lejos_en', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Izquierdo - en (Lejos)')),
                ('ojo_izquierdo_lejos_alt', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Izquierdo - ALT (Lejos)')),
                ('cristal_lejos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cristal (Lejos)')),
                ('armazon_lejos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Armazón (Lejos)')),
                ('ojo_derecho_cerca_esf', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Derecho - Esf (Cerca)')),
                ('ojo_derecho_cerca_cil', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Derecho - Cil (Cerca)')),
                ('ojo_derecho_cerca_en', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Derecho - en (Cerca)')),
                ('ojo_derecho_cerca_dip', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Derecho - Dip (Cerca)')),
                ('ojo_izquierdo_cerca_esf', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Izquierdo - Esf (Cerca)')),
                ('ojo_izquierdo_cerca_cil', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Izquierdo - Cil (Cerca)')),
                ('ojo_izquierdo_cerca_en', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Izquierdo - en (Cerca)')),
                ('ojo_izquierdo_cerca_alt', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ojo Izquierdo - ALT (Cerca)')),
                ('cristal_cerca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cristal (Cerca)')),
                ('armazon_cerca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Armazón (Cerca)')),
                ('receta_doctor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Receta Dr')),
                ('obra_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='O.O.S.S')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('como_nos_conocio', models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Cómo nos conoció?')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
                ('seña', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Seña')),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
